version: '2'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8484:8484

  config-service:
    build: config-service/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8383:8383

  zuul-apigateway:
    build: zuul-apigateway/
    depends_on:
      - config-service
      - eureka-server
      - music-service
      - user-service
    restart: always
    network_mode: "host"

    hostname: localhost
    ports:
      - 8282:8282

  music-service:
    build: music-service/
    restart: always
    network_mode: "host"
    ports:
      - 8090:8090
    depends_on:
      - config-service
      - eureka-server

  user-service:
    build: user-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8091:8091
    depends_on:
      - config-service
      - eureka-server

